// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtidPxpQb4PbZJFEChb_0B3Dwt7mqO18',
    appId: '1:648777948964:web:6f355b8bae1f5968fa5db1',
    messagingSenderId: '648777948964',
    projectId: 'mp-project-lab',
    authDomain: 'mp-project-lab.firebaseapp.com',
    storageBucket: 'mp-project-lab.firebasestorage.app',
    measurementId: 'G-5HRSL2RJMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtE-h0qgiaXbh5r5abu-48k-BAXAGamJ8',
    appId: '1:648777948964:android:5f2cfddea11f6c92fa5db1',
    messagingSenderId: '648777948964',
    projectId: 'mp-project-lab',
    storageBucket: 'mp-project-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQNwYyum05M_wEkucPNn8MEYt67LNJOZ8',
    appId: '1:648777948964:ios:d5ab109e2baa6fb7fa5db1',
    messagingSenderId: '648777948964',
    projectId: 'mp-project-lab',
    storageBucket: 'mp-project-lab.firebasestorage.app',
    iosBundleId: 'com.example.mpLabFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQNwYyum05M_wEkucPNn8MEYt67LNJOZ8',
    appId: '1:648777948964:ios:d5ab109e2baa6fb7fa5db1',
    messagingSenderId: '648777948964',
    projectId: 'mp-project-lab',
    storageBucket: 'mp-project-lab.firebasestorage.app',
    iosBundleId: 'com.example.mpLabFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtidPxpQb4PbZJFEChb_0B3Dwt7mqO18',
    appId: '1:648777948964:web:ac20e1d2c68e012bfa5db1',
    messagingSenderId: '648777948964',
    projectId: 'mp-project-lab',
    authDomain: 'mp-project-lab.firebaseapp.com',
    storageBucket: 'mp-project-lab.firebasestorage.app',
    measurementId: 'G-323R4V78DM',
  );
}
