import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:mp_lab_firebase/screens/home_screen.dart';
import 'package:mp_lab_firebase/screens/reset_password_screen.dart';
import 'package:mp_lab_firebase/screens/signup_screen.dart';
import 'firebase_options.dart';

// IMPORTANT: Add your Firebase options (google-services.json / GoogleService-Info.plist)
// Or use firebase_options.dart generated by flutterfire CLI if available.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}

final _auth = FirebaseAuth.instance;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(
      primarySwatch: Colors.indigo,
      textTheme: GoogleFonts.manropeTextTheme(),
      inputDecorationTheme: InputDecorationTheme(
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
      ),
    );

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Firebase Practice',
      theme: theme,
      home: AuthGate(),
    );
  }
}

/// Shows SignIn if not signed in, otherwise HomeScreen.
class AuthGate extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: _auth.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        final user = snapshot.data;
        if (user == null) return SignInScreen();
        return HomeScreen(user: user);
      },
    );
  }
}

/// ---------- Sign In Screen (Exercise 1 & 4 + Reset link) ----------
class SignInScreen extends StatefulWidget {
  @override
  State<SignInScreen> createState() => _SignInScreenState();
}

class _SignInScreenState extends State<SignInScreen> {
  final _formKey = GlobalKey<FormState>();
  final _emailCtl = TextEditingController();
  final _passCtl = TextEditingController();
  bool _loading = false;

  Future<void> _signIn() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _loading = true);
    try {
      await _auth.signInWithEmailAndPassword(email: _emailCtl.text.trim(), password: _passCtl.text);
      // On success, AuthGate will detect and navigate to HomeScreen
    } on FirebaseAuthException catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.message ?? 'Sign in failed')));
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    _emailCtl.dispose();
    _passCtl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Sign In')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            const SizedBox(height: 24),
            Form(
              key: _formKey,
              child: Column(children: [
                TextFormField(
                  controller: _emailCtl,
                  keyboardType: TextInputType.emailAddress,
                  decoration: const InputDecoration(labelText: 'Email'),
                  validator: (v) {
                    if (v == null || v.trim().isEmpty) return 'Email required';
                    final emailRegex = RegExp(r'^[^@]+@[^@]+\.[^@]+');
                    if (!emailRegex.hasMatch(v.trim())) return 'Enter a valid email';
                    return null;
                  },
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _passCtl,
                  obscureText: true,
                  decoration: const InputDecoration(labelText: 'Password'),
                  validator: (v) {
                    if (v == null || v.isEmpty) return 'Password required';
                    if (v.length < 6) return 'Password must be >= 6 chars';
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                SizedBox(
                  width: double.infinity,
                  child: CustomButton(
                    label: _loading ? 'Signing in...' : 'Login',
                    onTap: _loading ? null : _signIn,
                    enabled: !_loading,
                    showLoading: _loading,
                  ),
                ),
                const SizedBox(height: 8),
                Align(
                  alignment: Alignment.centerRight,
                  child: TextButton(
                    onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => ResetPasswordScreen())),
                    child: const Text('Forgot Password?'),
                  ),
                ),
                const SizedBox(height: 8),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text("Don't have an account?"),
                    TextButton(
                      onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => SignUpScreen())),
                      child: const Text('Register'),
                    ),
                  ],
                )
              ]),
            ),
          ],
        ),
      ),
    );
  }
}



/// ---------- Custom Button Widget (Exercise 8 + used for loading - Exercise 9) ----------
class CustomButton extends StatefulWidget {
  final String label;
  final VoidCallback? onTap;
  final bool enabled;
  final bool showLoading;

  const CustomButton({
    required this.label,
    required this.onTap,
    this.enabled = true,
    this.showLoading = false,
    Key? key,
  }) : super(key: key);

  @override
  State<CustomButton> createState() => _CustomButtonState();
}

class _CustomButtonState extends State<CustomButton> with SingleTickerProviderStateMixin {
  double _scale = 1.0;
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (_) {
        if (widget.enabled) setState(() => _scale = 0.98);
      },
      onTapUp: (_) {
        if (widget.enabled) setState(() => _scale = 1.0);
      },
      onTapCancel: () {
        if (widget.enabled) setState(() => _scale = 1.0);
      },
      onTap: widget.enabled ? widget.onTap : null,
      child: AnimatedScale(
        duration: const Duration(milliseconds: 100),
        scale: _scale,
        child: ElevatedButton(
          onPressed: widget.enabled ? widget.onTap : null,
          style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14)),
          child: widget.showLoading
              ? Row(mainAxisAlignment: MainAxisAlignment.center, children: const [
            SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2)),
            SizedBox(width: 12),
            Text('Please wait...'),
          ])
              : Text(widget.label),
        ),
      ),
    );
  }
}

